version: "3.9"

services:
  rooms:
    image: cadin7/room-app:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/rooms?retryWrites=true&w=majority&authSource=admin
    container_name: rooms-app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
    - /tmp/mongodata:/data/db
    container_name: mongodb
