version: "3.9"

services:
  trains:
    image: trains:1.0
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/trains?retryWrites=true&w=majority&authSource=admin
    container_name: trains-app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
    - /tmp/mongodata:/data/db
    container_name: mongodb